//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaCategory
    {
        public int id { get; set; }
        public int position { get; set; }
        public string Name { get; set; }
        public int idArea { get; set; }
    
        public virtual area area { get; set; }
    }
}
