//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public area()
        {
            this.AreaCategories = new HashSet<AreaCategory>();
            this.CoordinatesReferences = new HashSet<CoordinatesReference>();
            this.defects = new HashSet<defect>();
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
            this.parts = new HashSet<part>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string shop { get; set; }
        public string process { get; set; }
    
        public virtual ICollection<AreaCategory> AreaCategories { get; set; }
        public virtual ICollection<CoordinatesReference> CoordinatesReferences { get; set; }
        public virtual ICollection<defect> defects { get; set; }
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
        public virtual ICollection<part> parts { get; set; }
    }
}
