//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorCode
    {
        public ColorCode()
        {
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
        }
    
        public int id { get; set; }
        public string color { get; set; }
    
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
    }
}
