//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public location()
        {
            this.CoordinatesReferences = new HashSet<CoordinatesReference>();
            this.countermeasures = new HashSet<countermeasure>();
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int seq { get; set; }
        public Nullable<int> partId { get; set; }
        public int active { get; set; }
        public string shop { get; set; }
        public string process { get; set; }
    
        public virtual ICollection<CoordinatesReference> CoordinatesReferences { get; set; }
        public virtual ICollection<countermeasure> countermeasures { get; set; }
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
        public virtual part part { get; set; }
    }
}
