//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        public part()
        {
            this.countermeasures = new HashSet<countermeasure>();
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
            this.locations = new HashSet<location>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int seq { get; set; }
        public int active { get; set; }
        public Nullable<int> idArea { get; set; }
        public string shop { get; set; }
        public string process { get; set; }
        public Nullable<int> idOverflow { get; set; }
    
        public virtual area area { get; set; }
        public virtual ICollection<countermeasure> countermeasures { get; set; }
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
        public virtual ICollection<location> locations { get; set; }
        public virtual OverflowResponsible OverflowResponsible { get; set; }
    }
}
