//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsibleGroup
    {
        public ResponsibleGroup()
        {
            this.responsibles = new HashSet<responsible>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<responsible> responsibles { get; set; }
    }
}
