//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsible
    {
        public responsible()
        {
            this.countermeasures = new HashSet<countermeasure>();
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string shop { get; set; }
        public string process { get; set; }
        public Nullable<bool> active { get; set; }
        public string email { get; set; }
        public Nullable<int> responsibleGroup { get; set; }
    
        public virtual ICollection<countermeasure> countermeasures { get; set; }
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
        public virtual ResponsibleGroup ResponsibleGroup1 { get; set; }
    }
}
