//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class round
    {
        public int Round1 { get; set; }
        public string Shift { get; set; }
        public System.TimeSpan Start_time { get; set; }
        public System.TimeSpan Finish_time { get; set; }
        public Nullable<bool> Usage { get; set; }
        public string Name { get; set; }
        public int id { get; set; }
    }
}
