//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.countermeasures = new HashSet<countermeasure>();
            this.countermeasures1 = new HashSet<countermeasure>();
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
            this.userRolesMappings = new HashSet<userRolesMapping>();
        }
    
        public string id { get; set; }
        public string password { get; set; }
        public string user_name { get; set; }
        public string role { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<bool> active { get; set; }
        public string department { get; set; }
        public string email { get; set; }
        public bool isPic { get; set; }
    
        public virtual ICollection<countermeasure> countermeasures { get; set; }
        public virtual ICollection<countermeasure> countermeasures1 { get; set; }
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
        public virtual ICollection<userRolesMapping> userRolesMappings { get; set; }
    }
}
