//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQISService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingCoordinate
    {
        public WeldingCoordinate()
        {
            this.countermeasures = new HashSet<countermeasure>();
            this.FEEDBACK_DATA = new HashSet<FEEDBACK_DATA>();
        }
    
        public int idCoordinate { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> idPart { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<double> xmin { get; set; }
        public Nullable<double> xmax { get; set; }
        public Nullable<double> ymin { get; set; }
        public Nullable<double> ymax { get; set; }
        public string coordinate { get; set; }
    
        public virtual ICollection<countermeasure> countermeasures { get; set; }
        public virtual ICollection<FEEDBACK_DATA> FEEDBACK_DATA { get; set; }
    }
}
